name: Confirm Push

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploy:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: copy 
      run: |
        cowsay "$(date)" 

    - name: mariadb 
      run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -n -S apt install mariadb-server
    
    - name: tar 
      run: tar -xvf writefreely_0.14.0_linux_amd64.tar.gz